version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: rpgdatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    logging:
      driver: json-file
    environment:
      - POSTGRES_PASSWORD=DBPassword